### ISSUE TITLE
%<-% should also do regular assignment

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#17]
For consistency

**Comment by nteetor** [comment]
@pteetor and I had a lengthy back and forth about this early on in development. Our conclusion was `%<-%` replicates the multiple, unpacking, destructuring assignment of Python's or JS's `=` operator, but because `<-` and `=` already exist in R we did not want to include regular assignment behaviour.

Is your suggestion to make `%<-%` fully replicate Python's or JS's `=` operator, thereby making it consistent with its inspiration?

(in general I try to avoid using "should" 😉  too much of a guilt word)

**Comment by hadley** [comment]
Yes.

**Comment by nteetor** [comment]
@pteetor, when you have a moment, do you have any thoughts?

I think this and #21 are very intertwined.
