### ISSUE TITLE
Inconsistent error messages

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#19]
``` r
library(zeallot)
{x} %<-% list(1, 2)
#> Error: too many values to unpack
{x : y : z : a } %<-% list(1, 2)
#> Error: expecting 4 values, but found 2
```

**Comment by hadley** [comment]
A couple more:

``` r
library(zeallot)

{x} %<-% list()
{x : y} %<-% list()
#> Error: cannot de-structure list
```

I also think it would be useful to include `%<-%` in the error message

**Comment by nteetor** [comment]
You are absolutely right that the error messages need to incorporate `"%<-%"` somewhere in them.

In general, the error messages were modeled after Python's error messages. 

Your first example translated over to Python produces the message below.
```python
#>>> [x] = [1, 2]
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#ValueError: too many values to unpack
```
I built the `%<-%` operator to assume the LHS is correct, thus there are "too many values", not "too few variables", when the RHS has too many values to unpack. This could be elucidated with a better error message. 

Similarly, because the LHS is assumed to be correct, when the RHS contains too few values, an error is raised pointing the blame at the RHS.
```R
{x : y : z : a } %<-% list(1, 2)
#> Error: expecting 4 values, but found 2
```
The LHS expected 4 values, but the RHS only provided 2. An error message along that line might be better suited.

**Comment by hadley** [comment]
I think all these errors are related to a mismatch between the number of elements on the LHS and RHS, and so should use the same text. I don't think there's a need to mimic python's inconsistencies.

**Comment by nteetor** [comment]
That's fair, always striving to be better. The hope was the different messages help the user identify different problems, but if the messages are counter intuitive then they're self-defeating.
