### ISSUE TITLE
I don’t understand destructuring

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#38]
Why does data frame need a method? That seems weird to me (especially since the default method throws an error - how do regular lists get handled?)

**Comment by nteetor** [comment]
** following up on our brief conversation

## the trouble with vectors

When designing zeallot I imagined lists as the lowest common object. Unfortunately this is not intuitive in R because of vectors. In other languages a list of numbers or strings is just that. In R we can have a list or vector of these elements.

## lowest common object

The simplest benefit of using lists as the lowest common object is assigning vectors. `list(c(1, 2), c("a", "b"))` is 2 values not 4. The importance of lists for the `%<-%` operator and the `pair_off()` function can be described as follows, 

1. a list may have elements to assign to variables
1. a list may be an element to assign
1. a list may be recursively traversed

```R
c(x, y) %<-% list(2, 3)
# or
c(x, c(y, z)) %<-% list(2, list(3, 4))
# or
c(c(x)) %<-% list(list(2, 3))
```

`pair_off()` traverses two lists of the names and values simultaneously. The above considerations drive how pair_off destructures objects, raises errors, and how to recurse. 

## list columns

This is where I messed up. I completely ignored the implications of list columns. With list columns a data frame satisfies the three considerations listed above. Previously, mistakenly, I would have said they did not satisfy the third point. For this reason I would consider removing the `destructure.data.frame` implementation. Instead, data frames would be handled internally as lists are. 

## destructure() generic

I decided early on I did not want to implicitly destructure list-like objects. However, I assumed some users _would_ want to unpack list-like objects. Thus, I provide the destructure generic. The method is called when 1. there is a mismatch between the number of names and values and 2. the "values" are actually a list with a single element, see pair-off.R. `destructure()` is called in an attempt to resolve the mismatch. Objects are only destructured when necessary so as to satisfy the number of variables specified. 

I do not mind that the default implementation raises an error, however I think we might agree the wrong error is being raised. I could remove the default implementation altogether. `pair_off()` would catch a no implementation error and raise an incorrect number of values error. The user is left with the more appropriate no implementation error when calling destructure from the console.
