### ISSUE TITLE
%<-% and %>%

### ISSUE THREAD

**Issue by t-kalinowski** [nteetor/zeallot#43]
Would it be possible to make `%<-%` work with `%>%` chains on the left hand side?

**Comment by nteetor** [comment]
I brought up this concern in https://github.com/tidyverse/magrittr/issues/137. I also put together a pull request. However, I never received a response. However there are some bigger implications as the `%>%` would give precedence to _any_ custom infix function. At the time I felt `%->%` solved most of the problem. If you really want to use `%<-%` I currently recommend putting parentheses around any pipe chains.

**Comment by vlepori** [comment]
Was this ever addressed? Currently `%<-%` still has precedence over `%>%`. Is there a precise reason for this behaviour? (especially as it is not consistent with `%>%` precedence over `<-`).
I am really not a fan of right-hand assignments, they make code harder to read.

**Comment by nteetor** [comment]
Hello @vlepori, the magrittr issue got nowhere. I closed it and, call me pessimistic, I wouldn't expect anything to change in magrittr. 

##### re: behaviour 

This behaviour happens because the two operators are both infix operators. You can refer to [this page](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html) for more on R's operator precedence. 

You can think of them as + and -. The two have the same precedence, so it comes down to order. Thus, the assignment operation happens first. In R, an assignment operation silently returns the value assigned. So, the silently returned value is passed down the magrittr chain without a further assignment operation.
